### ISSUE TITLE
Instructions for user and developer

### ISSUE THREAD

**Issue by tomerkay** [TechnionYearlyProject/SummitBTW#132]
As discussed in the weekly meeting we need to add Instructions for user and developer.

**Comment by EylonSho** [comment]
@tomerkay 
For installing python dependencies - requirements should be a txt file.
see this: https://devcenter.heroku.com/articles/python-pip

**Comment by EylonSho** [comment]
Moreover `logging` is already installed in python by default.
But an actual problem - there are dependencies that are not covered in requirements.
Such as **Flask** and others.

**Comment by EylonSho** [comment]
I used `pipreqs` to generate requirements.txt file.
The command:
`pipreqs  --ignore sumo_tweaks,materials,management/gui/static .`
