### ISSUE TITLE
Streaming SUMO GUI

### ISSUE THREAD

**Issue by yairf11** [TechnionYearlyProject/SummitBTW#153]
As we talked about in our last meeting, we need to stream the SUMO GUI through a web app, such that it could be run from an Azure server. 

We (@gdor80 and myself) have decided to use the following approach: The SUMO GUI will be run normally in the server, and episodic screenshots will be taken. We will then add controlling options through the web app, send the commands back through TraCI and display the changes by screen-shooting the GUI and sending the updated images to the web client. 

Therefore, the next goals are to be able to take these screenshots, save them to a local file, and then send them to the web client.

**Comment by gdor80** [comment]
As we said, Nope.
