### ISSUE TITLE
Setup Azure Web App

### ISSUE THREAD

**Issue by EylonSho** [TechnionYearlyProject/SummitBTW#156]
As part of the deployment of our project to a full server-client system, we need to set up an azure web server (as a service).
It includes server side panel management, storage, as well as proper communication with the backend and SUMO engine.

**Comment by rany11** [comment]
Note the machine in the Azure cloud is 32 bit. So the sumo.exe should be 32 bit version

**Comment by EylonSho** [comment]
Seen that, thanks. That's necessary for the correct SUMO version to be installed.

**Comment by EylonSho** [comment]
I am pleased to announce that SUMO is successfully installed on azure.
Next goal: Integrating UNITY GUI into the website.
