### ISSUE TITLE
key error in get_statistics

### ISSUE THREAD

**Issue by EylonSho** [TechnionYearlyProject/SummitBTW#169]
I get the following error:

```
File "/Users/EylonSho/Nextcloud/Technion/YearlyProject/SummitBTW/statistics/get_statistics.py", line 26, in __init__
    self.waitingTime = float(parsed_info['waitingTime'])
KeyError: 'waitingTime'
```

**Comment by EylonSho** [comment]
I get this error in the example of `Big City` from the web GUI.

**Comment by tomerkay** [comment]
http://sumo.dlr.de/wiki/Downloads#SUMO_-_Latest_Development_Version

**Comment by EylonSho** [comment]
It turns out that `neighborhood` and `big city` examples' format is not updated to the current sumo version.
