### ISSUE TITLE
Delivering data from E2 (lane-area) detectors

### ISSUE THREAD

**Issue by EylonSho** [TechnionYearlyProject/SummitBTW#40]
After adding detectors to a SUMO network #39, need to fetch data from induction loops detectors (see #23), and deliver it to the algorithmic layer.

**Comment by EylonSho** [comment]
Editing the title, following the decision to work with lane-area detectors

**Comment by EylonSho** [comment]
For now we will keep this issue active since we might want extend the API for the scheduler.
@rany11 Let me know if you need any other parameters for the algorithm.
You can use the following list for ideas:

Name | Type | Description
-- | -- | --
begin | (simulation) seconds | The first time step the values were collected in
end | (simulation) seconds | The last time step + DELTA_T the values were collected in (may be equal to begin)
id | id | The id of the detector (needed if several detectors share an output file)
sampledSeconds | s | The total time all vehicles which contributed data were on the detector. this may be fractional even if the time step is one second, because the times when the vehicle enters and leaves are interpolated.
nVehEntered | # | The number of vehicles that entered the detector in the corresponding interval.
nVehLeft | # | The number of vehicles that left the detector in the corresponding interval.
nVehSeen | # | The number of vehicles that were on the detector in the corresponding interval (were "seen" by the detector).
meanSpeed | m/s | The mean velocity over all collected data samples.
meanTimeLoss | s | The average time loss per vehicle in the corresponding interval. The total time loss can be obtained by multiplying this value with nVehSeen.
meanOccupancy | % | The percentage (0-100%) of the detector's place that was occupied by vehicles, summed up for each time step and averaged by the interval duration.
maxOccupancy | % | The maximum percentage (0-100%) of the detector's place that was occupied by vehicles during the interval.
meanMaxJamLengthInVehicles | #vehicles | The length of the longest jams recognized during each step, averaged over the interval duration. In vehicles that have contributed to these jams.
meanMaxJamLengthInMeters | m | As prior, but in meters (see notes)
maxJamLengthInVehicles | #vehicles | The length of the longest jam recognized during the interval duration. In vehicles that have contributed to this jams.
maxJamLengthInMeters | m | As prior, but in meters (see notes)
jamLengthInVehiclesSum | #vehicles | The sum of all lengths of all jams recognized during the interval. In vehicles that have contributed to these jams.
jamLengthInMetersSum | m | As prior, but in meters (see notes)
meanHaltingDuration | s | The mean halting duration of vehicles that entered the area and are still inside or have left the area within the reported interval.
maxHaltingDuration | s | The maximum halting duration of vehicles that entered the area and are still inside or have left the area within the reported interval.
haltingDurationSum | s | The sum of all halting durations of vehicles that entered the area and are still inside or have left the area within the reported interval.
meanIntervalHaltingDuration | s | The mean halting duration of vehicles that entered the area and are still inside or have left the area within the reported interval, counted from the interval's begin.
maxIntervalHaltingDuration | s | The maximum halting duration of vehicles that entered the area and are still inside or have left the area within the reported interval, counted from the interval's begin.
intervalHaltingDurationSum | s | The sum of all halting durations of vehicles that entered the area and are still inside or have left the area within the reported interval, counted from the interval's begin.
startedHalts | # | The number of started halts. Please note that during an interval a vehicle may stop halting and enter a new halting state.
meanVehicleNumber | # | The mean number of vehicles that were on the detector (averaged over the interval duration).
maxVehicleNumber | # | The maximum number of vehicles that were on the detector area during the interval.

**Comment by tomerkay** [comment]
associated commit 697934303d37f3ac948105b9c826f4e7f190cd54

**Comment by EylonSho** [comment]
Closing for now.
Please reopen if you need to get more information from detectors.
