### ISSUE TITLE
Logger

### ISSUE THREAD

**Issue by tomerkay** [TechnionYearlyProject/SummitBTW#57]
@gdor80 and I are working on the logger for the municipality module . We are using this library [logger](https://docs.python.org/3/library/logging.html#logging.basicConfig) that can be used for other modules that works with python.

**Comment by EylonSho** [comment]
Consider using `import logging`, which is a built-in library of python:
https://docs.python.org/2/howto/logging.html.
I think that this is exactly what we all are looking for.
Let us know if we should use it too (or maybe other alternative).

**Comment by tomerkay** [comment]
It is what we are working with
