### ISSUE TITLE
Needs some information that could be retrieved from Junction

### ISSUE THREAD

**Issue by tomerkay** [TechnionYearlyProject/SummitBTW#75]
At the moment there are no statistics that could be retrieved. @yairf11 . Such as the average mean speed in it, number of cars, etc.

**Comment by yairf11** [comment]
Each detector provides information about its state, see https://github.com/TechnionYearlyProject/SummitBTW/blob/master/simulator/realtime/detector.py for the detectors' API. 
If you want to calculate averages for the junctions, you can do it externally - no need to over-complicate the junctions' API.
