### ISSUE TITLE
Creating Random cities ready for simulations

### ISSUE THREAD

**Issue by tomerkay** [TechnionYearlyProject/SummitBTW#76]
At the moment we can take any osm map of the world, transform it into net.xml for sumo, and then adjust the traffic lights manually because it can not be done automatically. Although we found good tools for all these three tasks, still I think we need a way to create simple cities automatically.

**Comment by EylonSho** [comment]
At the last time I checked. the conversion from OSM to SUMO network is not trivial since there are warnings in the conversion. Moreover, every road was set to permit traffic in any direction.
Let me know if you have succeeded to fix those warnings & network problems.

**Comment by EylonSho** [comment]
I'm in charge of this mission. See #78.
Closing.
