### ISSUE TITLE
vehicles are shown suprisingly in the network center from nowhere

### ISSUE THREAD

**Issue by EylonSho** [TechnionYearlyProject/SummitBTW#80]
in `simulator/preprocess/random_trips.py` script, the are also random trips that starts (and apparently ends) in the center of the map.
It seems as those vehicles appear from nowhere on the map.
However, we would like to make the simulation to be as real as possible.
Hence need to fix this by limiting the start & end points of trips to the margins of the map.

**Comment by tomerkay** [comment]
It is fixed by " fringe_factor=10000 "
