### ISSUE TITLE
simulator_real_time.py

### ISSUE THREAD

**Issue by tomerkay** [TechnionYearlyProject/SummitBTW#91]
At the moment there two files: simulator and simulator_real_time. simulator is the **OLD** one and you want to you use simulator_real_time. I am not deleting the old one just in case...
@rany11  there is a comment where you come in.
@gdor80  You need to work with the class RealTime. There is a functions that gives you the info you desire by the id of junction/detector. Just write a correct id.

Explanation of the logic:
There is the main thread that promotes the simulation and does the algo staff, and there is a secondary thread that waits for input from the user, and at the moment it prints the info of a junction/detector according to given id.
Please notice that there is a **lock** that the two threads wants to hold: because you can't make two requests from traci at the same time.
There is also an **EVENT** - when the simulation ends the main thread set the flag on the event. The secondary thread after receiving an input from client makes sure the simulation did not end, and if it did it exits. Notice that there is always a need to insert some input because it started to wait before the simulation ended, and forcing it to stop made some trouble.
Feel free to contact me with any problems.

**Comment by tomerkay** [comment]
@rany11 and @gdor80  notice there is **no** simulator_real_time.py but only simulator.py 
I took out RealTime into a different class - better decoupling

**Comment by yairf11** [comment]
I think this issue is a good example for why we need to maintain some sort of wiki or readme for the important scripts that are functioning as pipeline connectors, such as this one.

**Comment by EylonSho** [comment]
Wiki is targeted to for the user. So I agree with @yairf11, but should be readme in this case.
