### ISSUE TITLE
is_green Method for class detector

### ISSUE THREAD

**Issue by rany11** [TechnionYearlyProject/SummitBTW#96]
My algorithm assumes there is an is_green(self) method in class Detector that returns true iff the traffic light is green.

Not sure whether Yair or Eylon are responsible for this.

**Comment by yairf11** [comment]
Ran, please see the referenced commit. I added the method to the Junction class instead of the Detector class, I believe it doesn't matter to you. 
Close this issue if this is good enough for you.

**Comment by rany11** [comment]
All is good
