### ISSUE TITLE
Adapting New Scheduler Structure

### ISSUE THREAD

**Issue by yairf11** [TechnionYearlyProject/SummitBTW#97]
All schedulers need to be implemented as sub-classes of AbstractScheduler (#93). @rany11, please change your scheduler such that it conforms with this requirement.

**Comment by EylonSho** [comment]
@rany11 why have you changed the scheduler? now it is not inheriting from `AbstractScheduler` anymore...

**Comment by rany11** [comment]
You are correct, I fixed it
