### ISSUE TITLE
Correct usage of simulator.py

### ISSUE THREAD

**Issue by rany11** [TechnionYearlyProject/SummitBTW#99]
Due to new additions by @tomerkay the simulator.py script should be executed as follows:

1) run the script with the right parameter.
2) when the simulation is over, enter in the console a number (As a response to the message "Write id of object you are interested for")
3) In the sumo app, press on "Yes" (As a response to the "Simulation Ended" box that appeared).
4) Close the sumo app. (This will cause the termination of the execution of the script).
5) tripinfo_realtime.xml is ready in it's complete form.

This is a minor bug in the parallelism of the realtime statistic which caused this unwanted behavior (The sumo app doesn't terminate until an input is received to the realtime statistics thread).

**Comment by EylonSho** [comment]
This is critical and need to be fixed before presenting our demo.
 I've fixed the bug not-conventionally for now (using `_delete` method which is protected).
Currently we have this solution so we would be able to run simulations properly and get a valid tripinfo.xml file).
Keeping this issue open, to solve it later without using protected/private methods.

**Comment by EylonSho** [comment]
Assigning also @tomerkay to this issue since this bug must be solved properly by refining the threading logic of the realtime statistics.

**Comment by tomerkay** [comment]
It works fine now with the GUI real statistics.
